---

services:
  proxy:
    image: ghcr.io/applicreation/harmony-proxy:latest
    ports:
      - 80:80
  core:
    image: ghcr.io/applicreation/harmony-core:latest
    volumes:
      - ./.harmony:/root/.harmony:ro
  example:
    image: nginx:1-alpine
    volumes:
      - ./app:/usr/share/nginx/html:ro
