---

# @todo needs replacing with release
#release:
#  types:
#    - published

name: Release
on:
  push:
    branches:
      - main
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to GitHub Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          tags: |
            ghcr.io/${{ github.repository }}:v0.0.0
            ghcr.io/${{ github.repository }}:v0.0
            ghcr.io/${{ github.repository }}:v0
